GET http://localhost:5000/api/users

#login
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "kofi arhin",
    "email": "kofiarhin@gmail.com",
    "password": ""
}